String.toLocaleString({
    
	"it": {
		"%game-intro"           : "Join the <strong>Resistance!</strong>",
		"%restart-button"       : "Play Again",
		"%keep-playing-button"  : "Keep going",
		"%retry-button"         : "Retry",
		"%game-won"             : "You win!",
		"%game-over"            : "Lost The Game",
		"%game-explanation"     : "<strong class=\"important\">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two tiles with the same symbol touch, they <strong>get promoted!</strong>",
		"%disclaimer"           : "<strong class=\"important\">Note:</strong> This site <a href=\"http://git.io/cupcakes\">git.io/cupcakes</a> is a spin-off of the official version of <a href=\"http://git.io/2048\">2048</a> created by <a href=\"http://gabrielecirulli.com\" target=\"_blank\">Gabriele Cirulli</a>.",
		"%credits"              : "Resistance images by <a href=\"http://www.georgetowncupcake.com/\" title=\"Georgetown Cupcake | DC Cupcakes | About\">Georgetown Cupcake</a>.",
		"%tweet1"               : "I scored \"",
		"%tweet2"               : "\" at 2048-CUPCAKES #2048game",
		"%tile-legend"          : "<strong class=\"important\">Tile Legend:</strong>",
		'%2'                    : 'The People',
    '%4'                    : 'Consumerism',
    '%8'                    : 'Mass Media',
    '%16'                   : 'Police State',
    '%32'                   : 'The Military',
    '%64'                   : 'Justice System',
    '%128'                  : 'Corporations',
    '%256'                  : 'Big Banks',
    '%512'                  : 'The Government',
    '%1024'                 : 'The Plutocrats',
    '%2048'                 : 'The Illuminati',
		'%p0'                   : 'The People',
    '%p4'                   : 'Consumerism',
    '%p8'                   : 'Mass Media',
    '%p16'                  : 'Police State',
    '%p32'                  : 'The Military',
    '%p64'                  : 'Justice System',
    '%p128'                 : 'Corporations',
    '%p256'                 : 'Big Banks',
    '%p512'                 : 'The Government',
    '%p1024'                : 'The Plutocrats',
    '%p2048'                : 'The Illuminati',
	},
	
	"en": {
		"%game-intro"           : "Join the <strong>Cupcakes!</strong>",
		"%restart-button"       : "Restart",
		"%keep-playing-button"  : "Keep going",
		"%retry-button"         : "Retry",
		"%game-won"             : "You win!",
		"%game-over"            : "Game over!",
		"%game-explanation"     : "<strong class=\"important\">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two tiles with the same symbol touch, they <strong>get promoted!</strong>",
		"%disclaimer"           : "<strong class=\"important\">Note:</strong> This site <a href=\"http://git.io/cupcakes\">git.io/cupcakes</a> is a spin-off of the official version of <a href=\"http://git.io/2048\">2048</a> created by <a href=\"http://gabrielecirulli.com\" target=\"_blank\">Gabriele Cirulli</a>.",
		"%credits"              : "Cupcakes images by <a href=\"http://www.georgetowncupcake.com/\" title=\"Georgetown Cupcake | DC Cupcakes | About\">Georgetown Cupcake</a>.",
		"%tweet1"               : "I scored \"",
		"%tweet2"               : "\" at 2048-CUPCAKES #2048game",
		"%tile-legend"          : "<strong class=\"important\">Tile Legend:</strong>",
		'%2'                    : 'The People',
    '%4'                    : 'Consumerism',
    '%8'                    : 'Mass Media',
    '%16'                   : 'Police State',
    '%32'                   : 'The Military',
    '%64'                   : 'Justice System',
    '%128'                  : 'Corporations',
    '%256'                  : 'Big Banks',
    '%512'                  : 'The Government',
    '%1024'                 : 'The Plutocrats',
    '%2048'                 : 'The Illuminati',
		'%p0'                   : 'The People',
    '%p4'                   : 'Consumerism',
    '%p8'                   : 'Mass Media',
    '%p16'                  : 'Police State',
    '%p32'                  : 'The Military',
    '%p64'                  : 'Justice System',
    '%p128'                 : 'Corporations',
    '%p256'                 : 'Big Banks',
    '%p512'                 : 'The Government',
    '%p1024'                : 'The Plutocrats',
    '%p2048'                : 'The Illuminati',
	}

});